# Generated by Django 6.0.3 on 2026-03-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('stream', models.CharField(max_length=1)),
                ('reg_boys', models.PositiveIntegerField(default=0)),
                ('reg_girls', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('present_boys', models.PositiveIntegerField()),
                ('present_girls', models.PositiveIntegerField()),
                ('permitted_boys', models.PositiveIntegerField(default=0)),
                ('permitted_girls', models.PositiveIntegerField(default=0)),
                ('absentee_names', models.TextField(blank=True, help_text='List names of truants here')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.schoolclass')),
            ],
        ),
    ]
