# Generated by Django 6.0.3 on 2026-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['level', 'stream'], 'verbose_name_plural': 'School Classes'},
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='absentee_names',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='truant_names',
            field=models.TextField(blank=True, verbose_name='Absentee Names (No Permission)'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='present_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='present_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5'), ('Form 6', 'Form 6')], max_length=10),
        ),
    ]
