# Generated by Django 6.0.3 on 2026-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_schoolclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='permitted_names',
            field=models.TextField(blank=True, help_text='Enter names separated by commas'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='truant_names',
            field=models.TextField(blank=True, help_text='Enter names separated by commas'),
        ),
    ]
