# Generated by Django 6.0.3 on 2026-03-21 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_permitted_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='school_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='truant_boys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='truant_girls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='permitted_names',
            field=models.TextField(blank=True, help_text='Names separated by commas'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='truant_names',
            field=models.TextField(blank=True, help_text='Names separated by commas'),
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
