# Generated by Django 6.0.3 on 2026-03-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerecord_school_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='total_boys_registered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_girls_registered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
