# Generated by Django 6.0.3 on 2026-03-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_total_boys_registered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tod_names', models.CharField(help_text='Names of the 2-3 teachers on duty', max_length=255)),
                ('arrival_time', models.TimeField()),
                ('compound_cleanliness', models.TextField(help_text='Which class? Any challenges?')),
                ('morning_sessions', models.TextField(help_text='Prep classes status/challenges')),
                ('lunch_details', models.TextField(help_text='Menu, preparation, and serving status')),
                ('evening_remedial', models.TextField(help_text='Evening classes and remedial status')),
                ('departure_time', models.TimeField()),
                ('maintenance_notes', models.TextField(help_text='Repairs, water, electricity, etc.')),
                ('overall_comments', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
