# Generated by Django 6.0.3 on 2026-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_dailytodreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytodreport',
            name='teacher_name',
            field=models.CharField(default='Unknown', help_text='Enter the name of the teacher submitting this report (for record-keeping and accountability purposes).', max_length=100, verbose_name="Teacher's Full Name"),
            preserve_default=False,
        ),
    ]
