# Generated by Django 6.0.3 on 2026-03-24 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_dailytodreport_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytodreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='dailytodreport',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Enter the name of the teacher submitting this report (for record-keeping and accountability purposes).', max_length=100, null=True, verbose_name="Teacher's Full Name"),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('school_class', 'date')},
        ),
    ]
