# Generated by Django 6.0.3 on 2026-04-02 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_notificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('workbook', models.FileField(upload_to='result_templates/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('sheet_name', models.CharField(blank=True, max_length=120)),
                ('header_row', models.PositiveIntegerField(default=13)),
                ('first_student_row', models.PositiveIntegerField(default=14)),
                ('last_student_row', models.PositiveIntegerField(default=14)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_result_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('centre_no', models.CharField(blank=True, max_length=20)),
                ('candidate_no', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=150)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.resulttemplate')),
            ],
            options={
                'ordering': ['row_number', 'candidate_no', 'student_name'],
                'unique_together': {('template', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ResultTemplateSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('column_letter', models.CharField(max_length=5)),
                ('column_index', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='attendance.resulttemplate')),
            ],
            options={
                'ordering': ['display_order', 'column_index', 'name'],
                'unique_together': {('template', 'column_index')},
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.CharField(blank=True, max_length=20)),
                ('is_final', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_result_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.resultstudent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.resulttemplate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.resulttemplatesubject')),
            ],
            options={
                'ordering': ['student__row_number'],
                'unique_together': {('template', 'subject', 'student')},
            },
        ),
    ]
