# Generated by Django 6.0.3 on 2026-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_resulttemplate_resultstudent_resulttemplatesubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], default='open', max_length=20),
        ),
    ]
