# Generated by Django 6.0.3 on 2026-04-23 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_default_school(apps, schema_editor):
    School = apps.get_model('attendance', 'School')
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    DailyTODReport = apps.get_model('attendance', 'DailyTODReport')
    NotificationLog = apps.get_model('attendance', 'NotificationLog')
    ResultTemplate = apps.get_model('attendance', 'ResultTemplate')
    SchoolMembership = apps.get_model('attendance', 'SchoolMembership')
    User = apps.get_model('auth', 'User')

    school, _ = School.objects.get_or_create(
        slug='mwandet-secondary-school',
        defaults={
            'name': 'Mwandet Secondary School',
            'portal_name': 'Mwandet Digital',
            'slogan': 'Quality and Excellence',
            'initiative_name': 'Naura Digital Initiative',
            'initiative_short_name': 'N.D.I',
            'is_active': True,
        },
    )

    AttendanceRecord.objects.filter(school__isnull=True).update(school=school)
    DailyTODReport.objects.filter(school__isnull=True).update(school=school)
    NotificationLog.objects.filter(school__isnull=True).update(school=school)
    ResultTemplate.objects.filter(school__isnull=True).update(school=school)

    for user in User.objects.all():
        group_names = set(user.groups.values_list('name', flat=True))
        if user.is_superuser:
            role = 'headmaster'
            can_manage_school = True
        elif 'Management' in group_names:
            role = 'management'
            can_manage_school = True
        elif 'Academic Office' in group_names:
            role = 'academic_office'
            can_manage_school = True
        else:
            role = 'teacher'
            can_manage_school = False

        SchoolMembership.objects.get_or_create(
            school=school,
            user=user,
            defaults={
                'role': role,
                'can_manage_school': can_manage_school,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_resulttemplate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_name', models.CharField(default='Naura Digital Initiative', max_length=150)),
                ('initiative_short_name', models.CharField(default='N.D.I', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('portal_name', models.CharField(blank=True, max_length=180)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('logo_with_background', models.FileField(blank=True, upload_to='schools/logos/')),
                ('logo_without_background', models.FileField(blank=True, upload_to='schools/logos/')),
                ('banner_image', models.FileField(blank=True, upload_to='schools/banners/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#0d3b66', max_length=7)),
                ('accent_color', models.CharField(default='#ffc107', max_length=7)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('website_domain', models.CharField(blank=True, max_length=255)),
                ('default_classes', models.TextField(blank=True, help_text='Optional comma-separated class list for this school.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='dailytodreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.school'),
        ),
        migrations.AddField(
            model_name='dailytodreport',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tod_reports', to='attendance.school'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='attendance.school'),
        ),
        migrations.AddField(
            model_name='resulttemplate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_templates', to='attendance.school'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('school', 'school_class', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailytodreport',
            unique_together={('school', 'date')},
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('headmaster', 'Headmaster'), ('management', 'Management'), ('academic_office', 'Academic Office'), ('teacher', 'Teacher')], default='teacher', max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('can_manage_school', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='attendance.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school__name', 'role', 'user__username'],
                'unique_together': {('school', 'user')},
            },
        ),
        migrations.RunPython(seed_default_school, migrations.RunPython.noop),
    ]
